---
- name: Restart pg_autoctl for archive settings
  ansible.builtin.systemd:
    name: "{{ pg_autoctl_service_name }}"
    state: restarted

- name: Restart hourly WAL archive timer
  ansible.builtin.systemd:
    name: postgresql-wal-archive-hourly.timer
    enabled: true
    state: restarted
    daemon_reload: true

- name: Reload systemd for WAL archive units
  ansible.builtin.systemd:
    daemon_reload: true
